# Generated by Django 2.1.1 on 2018-10-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0005_auto_20181016_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='classification',
            field=models.CharField(default='Others', max_length=64),
        ),
    ]
